// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type E2ePackMode = "happy" | "empty" | "error";
type E2eChallenge = { id: string; code: string; sender_name: string; pack_id: string };
type E2eAnswer = {
  id: string;
  challenge_id: string;
  question_id: string;
  session_token: string | null;
  score: number;
  verdict: string;
  question_text: string;
  answer_text: string;
  what_fumbled: string;
};
type E2eAnswerInput = Omit<E2eAnswer, "id">;
type E2eState = {
  challenges: E2eChallenge[];
  answers: E2eAnswer[];
};

const e2ePack = {
  id: "pack-worm",
  slug: "worm-test",
  name: "Worm Test",
  emoji: "🪱",
  description: "Transformation, identity, and classic impossible-love traps.",
  bg_color: "brand-pink",
};

const e2eQuestions = [
  {
    id: "question-worm",
    text: "Would you still love me if I was a worm?",
  },
  {
    id: "question-dance",
    text: "Would you still text me back if I lost the ability to text and could only communicate in interpretive dance?",
  },
];

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  if (import.meta.env.VITE_E2E_MOCK_SUPABASE === "true") {
    return createE2eSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function getE2eState(): E2eState {
  const globalScope = globalThis as typeof globalThis & { __DF_E2E_STATE__?: E2eState };
  globalScope.__DF_E2E_STATE__ ??= { challenges: [], answers: [] };
  return globalScope.__DF_E2E_STATE__;
}

export function recordE2eAnswerForResult(answer: E2eAnswerInput) {
  if (import.meta.env.VITE_E2E_MOCK_SUPABASE !== "true") return;

  const state = getE2eState();
  const existing = state.answers.find(
    (item) =>
      item.challenge_id === answer.challenge_id &&
      item.question_id === answer.question_id &&
      item.session_token === answer.session_token,
  );

  if (existing) {
    Object.assign(existing, answer);
    return;
  }

  state.answers.push({
    ...answer,
    id: `answer-${state.answers.length + 1}`,
  });
}

function getE2ePackMode(): E2ePackMode {
  if (typeof window === "undefined") return "happy";
  const mode = window.sessionStorage.getItem("df_e2e_pack_mode");
  return mode === "empty" || mode === "error" ? mode : "happy";
}

function createE2eSupabaseClient() {
  return {
    from(table: string) {
      return {
        select() {
          return createE2eQuery(table);
        },
        async insert(payload: unknown) {
          const state = getE2eState();
          if (table === "challenges") {
            const challenge = payload as E2eChallenge;
            state.challenges.push({ ...challenge, id: "challenge-1" });
          }
          if (table === "answers") {
            recordE2eAnswerForResult(payload as E2eAnswerInput);
          }
          return { data: null, error: null };
        },
        update(payload: unknown) {
          return createE2eUpdate(table, payload);
        },
      };
    },
    auth: {
      async getSession() {
        return { data: { session: null }, error: null };
      },
    },
  };
}

function createE2eUpdate(table: string, payload: unknown) {
  const filters = new Map<string, string>();

  return {
    eq(column: string, value: string) {
      filters.set(column, value);
      return this;
    },
    async select() {
      if (table !== "answers") return { data: [], error: null };

      const state = getE2eState();
      const updated: Array<{ id: string }> = [];
      state.answers = state.answers.map((answer) => {
        const matches =
          answer.challenge_id === filters.get("challenge_id") &&
          answer.question_id === filters.get("question_id") &&
          answer.session_token === filters.get("session_token");

        if (!matches) return answer;
        updated.push({ id: answer.id });
        return { ...answer, ...(payload as Partial<E2eAnswer>) };
      });

      return { data: updated, error: null };
    },
  };
}

function createE2eQuery(table: string) {
  const filters = new Map<string, string>();

  return {
    eq(column: string, value: string) {
      filters.set(column, value);
      return this;
    },
    async order() {
      return resolveE2eQuery(table, filters, false);
    },
    async maybeSingle() {
      return resolveE2eQuery(table, filters, true);
    },
  };
}

async function resolveE2eQuery(table: string, filters: Map<string, string>, single: boolean) {
  const state = getE2eState();

  if (table === "question_packs") {
    const mode = getE2ePackMode();
    if (mode === "error") {
      return { data: null, error: new Error("Supabase is taking a tiny nap") };
    }
    return { data: mode === "empty" ? [] : [e2ePack], error: null };
  }

  if (table === "challenges") {
    const code = filters.get("code");
    const challenge = state.challenges.find((item) => item.code === code);
    const data =
      challenge == null
        ? null
        : {
            ...challenge,
            question_packs: { name: e2ePack.name, emoji: e2ePack.emoji },
            answers: state.answers,
          };
    return { data: single ? data : data == null ? [] : [data], error: null };
  }

  if (table === "questions") {
    return { data: e2eQuestions, error: null };
  }

  if (table === "answers") {
    const answers = state.answers.filter((answer) => {
      const challengeId = filters.get("challenge_id");
      const sessionToken = filters.get("session_token");
      return (
        (challengeId == null || answer.challenge_id === challengeId) &&
        (sessionToken == null || answer.session_token === sessionToken)
      );
    });
    return { data: answers, error: null };
  }

  return { data: single ? null : [], error: null };
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
